version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/service_backend"
    labels:
      - "backend dependencies"
    target-branch: "backend"
    schedule:
      interval: "daily"
    reviewers:
      - "borjaest"