version: "3.7"

services:

  perf-backend-testing:
    build:
      context: .
      target: production
      dockerfile: Dockerfile.cicd
      args:
        INSTALL_PYTHON_VERSION: 3.8
        USER_ID: ${jenkins_user_id}
        USER_GROUP: ${jenkins_user_group}
    environment:
      FLASK_ENV: production
      BACKEND_URL: /api/v1
      FLASK_APP: autoapp.py
    volumes:
      - type: bind
        source: .
        target: /app
    # to avoid shutting down the container
    command: [ "tail", "-f", "/dev/null" ]
